# -*- coding: utf-8 -*-
"""Greenhouse Plant Growth Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/mahalakshmich/greenhouse-plant-growth-analysis.e5efb77e-7d3c-4305-b80c-906f930d62d5.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20250501/auto/storage/goog4_request%26X-Goog-Date%3D20250501T194822Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D061ba3666125783a50960b659428b4a04777b9d0a40a52da4e6c1f9625bded7eb1e8e21d2e3f862f34092449e84bf16626b9bb3f51b52f00118b55793b8c7f3f36b497db2369d225655ff40de467182d3a3eb5ba0341d0c288df136bd66da681ea09ea866cd630ee1f389b21424553b7892c2a1b135023dc12b7a927a699cfa96fc29614e718872e2032a7ab7ea8b12cff260e519b81e3d3eeae8f0929a9e51ccbef460796b62359bee19fe18977b2b795c90f07fe7889580d210d45a7c5b6791bd92e4f5a18ed9a8abfcf25383c27dc04bcfef569d6127cb2ef6bea20bc9027f6cf7678c7cb2b90eb5e2b487f290576efe1a39bd4d46ca9f9604bc4d7195f68
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
adilshamim8_greenhouse_plant_growth_metrics_path = kagglehub.dataset_download('adilshamim8/greenhouse-plant-growth-metrics')

print('Data source import complete.')

"""<img src="https://devra.ai/analyst/notebook/1830/image.jpg" style="width: 100%; height: auto;" />

<div style="text-align:center; border-radius:15px; padding:15px; color:white; margin:0; font-family: 'Orbitron', sans-serif; background: #2E0249; background: #11001C; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); overflow:hidden; margin-bottom: 1em;">
    <div style="font-size:150%; color:#FEE100"><b>Greenhouse Plant Growth Metrics Analysis</b></div>
    <div>This notebook was created with the help of <a href="https://devra.ai/ref/kaggle" style="color:#6666FF">Devra AI</a></div>
</div>

## Table of Contents

- [Introduction](#Introduction)
- [Data Loading](#Data-Loading)
- [Data Cleaning and Preprocessing](#Data-Cleaning-and-Preprocessing)
- [Exploratory Data Analysis](#Exploratory-Data-Analysis)
- [Predictive Modeling](#Predictive-Modeling)
- [Conclusion](#Conclusion)

## Introduction

Here we investigate the Greenhouse Plant Growth Metrics dataset. It may appear as a jumble of metrics at first glance, but beneath the surface lies valuable insight about plant growth under controlled conditions. The interplay of variables such as ACHP, PHR, and others could tell us a story of plant physiology—all while our predictor attempts to classify the plants. If you find these insights useful, please consider upvoting.
"""

# Commented out IPython magic to ensure Python compatibility.
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')  # Ensures backend compatibility in Kaggle environments
import matplotlib.pyplot as plt
plt.switch_backend('Agg')  # For cases when only plt is imported

import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.inspection import permutation_importance

# Ensure plots are rendered inline for Kaggle
# %matplotlib inline

# Set plot style for better aesthetics
sns.set(style='whitegrid')

"""## Data Loading

We begin by loading the dataset. The data file is located in the same directory as this notebook. Note that the CSV uses a comma delimiter and ASCII encoding.
"""

# Load the dataset
data_path = '/kaggle/input/greenhouse-plant-growth-metrics/Greenhouse Plant Growth Metrics.csv'
try:
    df = pd.read_csv(data_path, delimiter=',', encoding='ascii')
    print('Data loaded successfully.')
except Exception as e:
    print(f'Error loading data: {e}')

# Display the first few rows of the data (to be executed when running the notebook)
df.head()

"""## Data Cleaning and Preprocessing

In this section, we review the data types, inspect missing values, and perform any transformations if necessary. Since the dataset contains mainly numeric measurements accompanied by a couple of string columns (Random and Class), we ensure proper type conversion where needed.
"""

# Display basic info
df.info()

# Check for missing values
missing_values = df.isnull().sum()
print('Missing values in each column:')
print(missing_values)

# If missing values are found in numeric columns, we may choose to impute or remove observations
if missing_values.sum() > 0:
    # For the sake of this analysis, we'll fill numeric missing values with the column mean
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

    # For object types, fill missing values with a placeholder 'Unknown'
    object_cols = df.select_dtypes(include=['object']).columns
    df[object_cols] = df[object_cols].fillna('Unknown')
    print('Missing values were imputed.')
else:
    print('No missing values found.')

# Verify data types
print('\nData types after cleaning:')
print(df.dtypes)

"""## Exploratory Data Analysis

Now that the data is clean, we inspect the underlying patterns and relationships. We will visualize distributions, relationships among numeric variables, and the distribution of the class labels. Note that correlation heatmaps are only produced if there are four or more numeric variables, ensuring meaningful correlations.
"""

# Plot histogram for each numeric column
numeric_df = df.select_dtypes(include=[np.number])
numeric_columns = numeric_df.columns

for col in numeric_columns:
    plt.figure(figsize=(6,4))
    sns.histplot(df[col], kde=True)
    plt.title(f'Histogram of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
    plt.tight_layout()
    plt.show()

# Inspect the distribution of the 'Class' column using a count plot
plt.figure(figsize=(6,4))
sns.countplot(x='Class', data=df)
plt.title('Distribution of the Class Variable')
plt.xlabel('Class')
plt.ylabel('Count')
plt.tight_layout()
plt.show()

# Create a pair plot to explore relationships between numeric variables
sns.pairplot(numeric_df)
plt.suptitle('Pair Plot of Numeric Features', y=1.02)
plt.show()

# Create a correlation heatmap if we have enough numeric features (4 or more)
if numeric_df.shape[1] >= 4:
    plt.figure(figsize=(10,8))
    corr = numeric_df.corr()
    sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f')
    plt.title('Correlation Heatmap of Numeric Features')
    plt.tight_layout()
    plt.show()
else:
    print('Not enough numeric features for a meaningful heatmap.')

"""## Predictive Modeling

Now we move on to predicting the plant's class. Although the features are many, we use a Random Forest Classifier for its robust performance and ease of interpretation. We split the dataset, train the model, and evaluate its accuracy as well as inspect the confusion matrix. We also apply permutation importance to better understand feature significance.

A note on reproducibility: random seeds are set to ensure consistent results. In practice, tuning hyperparameters could yield even better predictions—something for future improvements.
"""

# Prepare data for modeling
# Our target variable is 'Class' and features are all other numeric features
X = df.drop(columns=['Class', 'Random'], errors='ignore')  # Exclude 'Random' if not informative
y = df['Class']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Instantiate and train the Random Forest Classifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Compute prediction accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Prediction Accuracy: {accuracy:.4f}')

# Plot the confusion matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.tight_layout()
plt.show()

# Permutation Importance to assess feature significance
r = permutation_importance(model, X_test, y_test, n_repeats=30, random_state=42)

importance_df = pd.DataFrame({
    'feature': X.columns,
    'importance': r.importances_mean
}).sort_values(by='importance', ascending=True)

plt.figure(figsize=(8,6))
plt.barh(importance_df['feature'], importance_df['importance'], color='skyblue')
plt.title('Permutation Importance of Features')
plt.xlabel('Mean Importance')
plt.tight_layout()
plt.show()

"""## Conclusion

We have successfully performed an exploratory analysis on the Greenhouse Plant Growth Metrics dataset. The analysis provided insights into variable distributions and interrelationships, and a predictive model was built to classify plant types. The Random Forest classifier achieved a respectable accuracy, and permutation importance offered a glimpse into which factors most influence plant classification.

Future work could include more detailed feature engineering, hyperparameter tuning, and even alternative modeling approaches to further refine the predictions. Thank you for checking out this notebook; if you found it useful, please upvote.
"""